package com.jkrm.fupin.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jkrm.fupin.bean.CacheFileBean;

import com.jkrm.fupin.db.CacheFileBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheFileBeanDaoConfig;

    private final CacheFileBeanDao cacheFileBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheFileBeanDaoConfig = daoConfigMap.get(CacheFileBeanDao.class).clone();
        cacheFileBeanDaoConfig.initIdentityScope(type);

        cacheFileBeanDao = new CacheFileBeanDao(cacheFileBeanDaoConfig, this);

        registerDao(CacheFileBean.class, cacheFileBeanDao);
    }
    
    public void clear() {
        cacheFileBeanDaoConfig.clearIdentityScope();
    }

    public CacheFileBeanDao getCacheFileBeanDao() {
        return cacheFileBeanDao;
    }

}
